apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo0
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-3fs
